# Food Cart Data

food_carts = [{
    "name": "Pig ‘N A Pen",
    "address": "NE 52nd Ave and Sandy Blvd",
    "monday_hours": "11:00 am - 7:00 pm",
    "tuesday_hours": "11:00 am - 7:00 pm",
    "wednesday_hours": "Closed",
    "thursday_hours": "11:00 am - 7:00 pm",
    "friday_hours": "11:00 am - 8:00 pm",
    "saturday_hours": "12:00 pm - 8:00 pm",
    "sunday_hours": "12:00 pm - 6:00 pm",
    "facebook": "https://www.facebook.com/pignapen/timeline",
    "twitter": "https://twitter.com/pignapenpdx",
    "website": "http://Pignapen.squarespace.com",
    "phone_number": "Not Provided",
    "tags": ["American"]
  },
  {
    "name": "Rajah’s Hawaiian Grill",
    "address": "SW 3rd and Washington St",
    "monday_hours": "10am - 4:00 pm",
    "tuesday_hours": "10am - 4:00 pm",
    "wednesday_hours": "10am - 4:00 pm",
    "thursday_hours": "10am - 4:00 pm",
    "friday_hours": "10am - 4:00 pm",
    "saturday_hours": "Closed",
    "sunday_hours": "Closed",
    "facebook": "https://www.facebook.com/RajahsGrill",
    "twitter": "Not Provided",
    "website": "Not Provided",
    "phone_number": "503-719-9018",
    "tags": ["Hawaiian"]
  },
  {
    "name": "Mole Prehispanic Cuisine",
    "address": "5885 NW St Helens Rd",
    "monday_hours": "11:00 am - 4:00 pm",
    "tuesday_hours": "11:00 am - 4:00 pm",
    "wednesday_hours": "11:00 am - 4:00 pm",
    "thursday_hours": "11:00 am - 4:00 pm",
    "friday_hours": "11:00 am - 4:00 pm",
    "saturday_hours": "Closed",
    "sunday_hours": "Closed",
    "facebook": "https://www.facebook.com/molepdx/timeline",
    "twitter": "http://twitter.com/MolePDX",
    "website": "Not Provided",
    "phone_number": "503-875-9134",
    "tags": ["Latin American"]
  },
  {
    "name": "Grandpa Jimmy’s Southern Fried Fish",
    "address": "NE 76th and Glisan St",
    "monday_hours": "Closed",
    "tuesday_hours": "11:00 am -2:30pm  and 4:30pm - 8:00 pm",
    "wednesday_hours": "11:00 am -2:30pm  and 4:30pm - 8:00 pm",
    "thursday_hours": "11:00 am -2:30pm  and 4:30pm - 8:00 pm",
    "friday_hours": "11:00 am -2:30pm  and 4:30pm - 8:00 pm",
    "saturday_hours": "12:00 pm - 8:00 pm",
    "sunday_hours": "Closed",
    "facebook": "https://www.facebook.com/Grandpa-Jimmys-482716598554754/",
    "twitter": "Not Provided",
    "website": "Not Provided",
    "phone_number": "Not Provided",
    "tags": ["Southern", "American"]
  },
  {
    "name": "Steve’s Dawg House",
    "address": "NE 52nd and Sandy Blvd",
    "monday_hours": "11:00 am - 3pm and 5pm - 7:00 pm",
    "tuesday_hours": "Closed",
    "wednesday_hours": "Closed",
    "thursday_hours": "11:00 am - 3pm and 5pm - 7:00 pm",
    "friday_hours": "11:00 am - 3pm and 5pm - 8:00 pm",
    "saturday_hours": "11:00 am - 7:00 pm",
    "sunday_hours": "11:00 am - 3pm",
    "facebook": "https://www.facebook.com/stevesdawghouse/timeline",
    "twitter": "Not Provided",
    "website": "http://stevesdawghouse.com/",
    "phone_number": "503-319-9405",
    "tags": ["American", "Hot Dogs"]
  },
  {
    "name": "Straits Kitchen",
    "address": "SE 11th and Tacoma St",
    "monday_hours": "11:00 am - 7:00 pm",
    "tuesday_hours": "11:00 am - 7:00 pm",
    "wednesday_hours": "Closed",
    "thursday_hours": "11:00 am - 7:00 pm",
    "friday_hours": "11:00 am - 7:00 pm",
    "saturday_hours": "11:00 am - 7:00 pm",
    "sunday_hours": "11:00 am - 7:00 pm",
    "facebook": "https://www.facebook.com/straitskitchenpdx",
    "twitter": "http://twitter.com/straitskitchpdx",
    "website": "http://www.straitskitchenpdx.com/",
    "phone_number": "971-325-7323",
    "tags": ["Malaysian"]
  },
  {
    "name": "MF Tasty",
    "address": "N Mississippi Ave and N Beech St",
    "monday_hours": "closed",
    "tuesday_hours": "closed",
    "wednesday_hours": "11:00 am - 8:00 pm",
    "thursday_hours": "11:00 am - 8:00 pm",
    "friday_hours": "11:00 am - 8:00 pm",
    "saturday_hours": "11:00 am - 8:00 pm",
    "sunday_hours": "11:00 am - 8:00 pm",
    "facebook": "https://www.facebook.com/MF-Tasty-129370023747504/timeline/",
    "twitter": "https://twitter.com/mftasty",
    "website": "http://mftasty.com",
    "phone_number": "602-740-8861",
    "tags": ["American", "Southwestern"]
  },
  {
    "name": "Momo House",
    "address": "5221 NE Sandy Blvd",
    "monday_hours": "11:00 am - 8:00 pm",
    "tuesday_hours": "11:00 am - 8:00 pm",
    "wednesday_hours": "11:00 am - 8:00 pm",
    "thursday_hours": "11:00 am - 8:00 pm",
    "friday_hours": "11:00 am - 8:00 pm",
    "saturday_hours": "11:00 am - 8:00 pm",
    "sunday_hours": "11:00 am - 8:00 pm",
    "facebook": "Not Provided",
    "twitter": "Not Provided",
    "website": "Not Provided",
    "phone_number": "503-764-5028",
    "tags": ["Tibetan", "Indian"]
  },
  {
    "name": "PDX Dönerländ",
    "address": "NE 7th and Killingsworth",
    "monday_hours": "Closed",
    "tuesday_hours": "Closed",
    "wednesday_hours": "11:30 am - 2:30 pm",
    "thursday_hours": "11:30 am - 2:30 pm",
    "friday_hours": "11:30 am - 2:30 pm",
    "saturday_hours": "12:00 pm - 9:00 pm",
    "sunday_hours": "12:00 pm - 9:00 pm",
    "facebook": "https://www.facebook.com/pdxdonerland",
    "twitter": "http://twitter.com/pdxdonerland",
    "website": "http://pdx-donerland.com",
    "phone_number": "Not Provided",
    "tags": ["Turkish", "German"]
  },
  {
    "name": "La Cubana",
    "address": "3405 SE 82nd Ave",
    "monday_hours": "Closed",
    "tuesday_hours": "11:00 am - 8:00 pm",
    "wednesday_hours": "11:00 am - 8:00 pm",
    "thursday_hours": "11:00 am - 8:00 pm",
    "friday_hours": "11:00 am - 8:00 pm",
    "saturday_hours": "11:00 am - 8:00 pm",
    "sunday_hours": "11:00 am - 8:00 pm",
    "facebook": "Not Provided",
    "twitter": "Not Provided",
    "website": "Not Provided",
    "phone_number": "503-754-4044",
    "tags": ["Cuban"]
  },
  {
    "name": "Chicharito’s Mexican Grill",
    "address": "SW 3rd and Washington St",
    "monday_hours": "10:30 am - 4:00 pm",
    "tuesday_hours": "10:30 am - 4:00 pm",
    "wednesday_hours": "10:30 am - 4:00 pm",
    "thursday_hours": "10:30 am - 4:00 pm",
    "friday_hours": "10:30 am - 4:00 pm",
    "saturday_hours": "10:30 am - 4:00 pm",
    "sunday_hours": "Closed",
    "facebook": "https://www.facebook.com/Chicharitospdx?fref=ts",
    "twitter": "Not Provided",
    "website": "Not Provided",
    "phone_number": "Not Provided",
    "tags": ["Mexican"]
  },
  {
    "name": "Mac & Trees",
    "address": "SW 10th and Washington St",
    "monday_hours": "11:00 am - 3:00 pm",
    "tuesday_hours": "11:00 am - 3:00 pm",
    "wednesday_hours": "11:00 am - 3:00 pm",
    "thursday_hours": "11:00 am - 3:00 pm",
    "friday_hours": "11:00 am - 3:00 pm",
    "saturday_hours": "11:00 am - 3:00 pm",
    "sunday_hours": "Closed",
    "facebook": "Not Provided",
    "twitter": "Not Provided",
    "website": "Not Provided",
    "phone_number": "Not Provided",
    "tags": ["American"]
  },
  {
    "name": "Rosita’s Place",
    "address": "3405 SE 82nd",
    "monday_hours": "Closed",
    "tuesday_hours": "11:00 am - 9:00 pm",
    "wednesday_hours": "11:00 am - 9:00 pm",
    "thursday_hours": "11:00 am - 9:00 pm",
    "friday_hours": "11:00 am - 9:00 pm",
    "saturday_hours": "11:00 am - 9:00 pm",
    "sunday_hours": "Closed",
    "facebook": "Not Provided",
    "twitter": "Not Provided",
    "website": "http://www.rositasplace.net/",
    "phone_number": "Not Provided",
    "tags": ["Mexican"]
  },
  {
    "name": "Matt’s BBQ",
    "address": "4709 NE Martin Luther King Jr Blvd",
    "monday_hours": "Closed",
    "tuesday_hours": "Closed",
    "wednesday_hours": "11:00 am - 7:00 pm",
    "thursday_hours": "11:00 am - 7:00 pm",
    "friday_hours": "11:00 am - 7:00 pm",
    "saturday_hours": "11:00 am - 6:00 pm",
    "sunday_hours": "Closed",
    "facebook": "https://www.facebook.com/mattsbbqpdx/",
    "twitter": "Not Provided",
    "website": "Not Provided",
    "phone_number": "516-314-4739",
    "tags": ["American", "Barbeque"]
  },
  {
    "name": "Back to Eden Bakery Cart",
    "address": "SE Division St and SE 28th Pl",
    "monday_hours": "8:00 am - 10:00 pm",
    "tuesday_hours": "8:00 am - 10:00 pm",
    "wednesday_hours": "8:00 am - 10:00 pm",
    "thursday_hours": "8:00 am - 10:00 pm",
    "friday_hours": "8:00 am - 10:00 pm",
    "saturday_hours": "8:00 am - 10:00 pm",
    "sunday_hours": "8:00 am - 10:00 pm",
    "facebook": "https://www.facebook.com/backtoedenbakery",
    "twitter": "http://twitter.com/Back_To_Eden",
    "website": "http://www.backtoedenbakery.com",
    "phone_number": "503-477-5022",
    "tags": ["Bakery"]
  },
  {
    "name": "503 Burger Co.",
    "address": "N Mississippi Ave and N Skidmore St",
    "monday_hours": "11:00 am - 3:00 pm",
    "tuesday_hours": "11:00 am - 3:00 pm",
    "wednesday_hours": "11:00 am - 3:00 pm",
    "thursday_hours": "11:00 am - 6:00 pm",
    "friday_hours": "12:00 pm - 9:00 pm",
    "saturday_hours": "12:00 pm - 9:00 pm",
    "sunday_hours": "12:00 am - 5:00 pm",
    "facebook": "https://www.facebook.com/503burger",
    "twitter": "Not Provided",
    "website": "http://www.503burger.com/",
    "phone_number": "503-912-4294",
    "tags": ["Burgers", "American"]
  },
  {
    "name": "The 9 Food & Drink",
    "address": "510 SE Martin Luther King Jr Blvd",
    "monday_hours": "11:00 am - 7:00 pm",
    "tuesday_hours": "11:00 am - 7:00 pm",
    "wednesday_hours": "11:00 am - 7:00 pm",
    "thursday_hours": "11:00 am - 7:00 pm",
    "friday_hours": "11:00 am - 7:00 pm",
    "saturday_hours": "11:00 am - 7:00 pm",
    "sunday_hours": "Closed",
    "facebook": "https://www.facebook.com/pages/The-9-Food-and-Drink/898649180197745?sk=info&tab=page_info",
    "twitter": "Not Provided",
    "website": "Not Provided",
    "phone_number": "415-335-8475",
    "tags": ["Indian", "Malaysian"]
  },
  {
    "name": "Kelvin’s Döner",
    "address": "SW 10th Ave and SW Alder St",
    "monday_hours": "11:00 am - 3:00 pm",
    "tuesday_hours": "11:00 am - 3:00 pm",
    "wednesday_hours": "11:00 am - 3:00 pm",
    "thursday_hours": "11:00 am - 3:00 pm",
    "friday_hours": "11:00 am - 3:00 pm",
    "saturday_hours": "Closed",
    "sunday_hours": "Closed",
    "facebook": "https://www.facebook.com/Kelvins-doner-1524694601131313/",
    "twitter": "Not Provided",
    "website": "Not Provided",
    "phone_number": "971-563-2511",
    "tags": ["Turkish", "German"]
  },
  {
    "name": "OMG Oregon Made Grub",
    "address": "1502 NW 19th Ave",
    "monday_hours": "11:00 am - 3:00 pm",
    "tuesday_hours": "11:00 am - 3:00 pm",
    "wednesday_hours": "11:00 am - 3:00 pm",
    "thursday_hours": "11:00 am - 3:00 pm",
    "friday_hours": "11:00 am - 3:00 pm",
    "saturday_hours": "Closed",
    "sunday_hours": "Closed",
    "facebook": "https://www.facebook.com/oregonmadegrub",
    "twitter": "http://twitter.com/OMGPDX",
    "website": "http://www.omgpdx.com/",
    "phone_number": "Not Provided",
    "tags": ["American"]
  },
  {
    "name": "Donut Byte Labs",
    "address": "12 SW 4th Ave",
    "monday_hours": "Closed",
    "tuesday_hours": "Closed",
    "wednesday_hours": "8:00 am - 6:00 pm",
    "thursday_hours": "8:00 am - 6:00 pm",
    "friday_hours": "8:00 am - 1:00 pm",
    "saturday_hours": "10:00 am - 1:00 pm",
    "sunday_hours": "11:00 am - 6:00 pm",
    "facebook": "https://www.facebook.com/donutbytelabs",
    "twitter": "http://twitter.com/Donutbytelabs",
    "website": "http://instagram.com/donutbytelabs",
    "phone_number": "503-801-7321",
    "tags": ["Donuts"]
  },
  {
    "name": "Anything’s Pastable",
    "address": "8145 SE 82nd Ave",
    "monday_hours": "Closed",
    "tuesday_hours": "11:00 am - 9:00 pm",
    "wednesday_hours": "11:00 am - 9:00 pm",
    "thursday_hours": "11:00 am - 9:00 pm",
    "friday_hours": "11:00 am - 10:00 pm",
    "saturday_hours": "11:00 am - 10:00 pm",
    "sunday_hours": "2:30 pm - 9:00 pm",
    "facebook": "https://www.facebook.com/pages/Anythings-Pastable/835380383209723",
    "twitter": "http://twitter.com/ourpastabiz",
    "website": "http://www.cartlandia.com",
    "phone_number": "503-740-4805",
    "tags": ["Italian"]
  },
  {
    "name": "Captured Beer Bus",
    "address": "113 SE 28th Ave",
    "monday_hours": "12:00 pm - 9:00 pm",
    "tuesday_hours": "12:00 pm - 9:00 pm",
    "wednesday_hours": "12:00 pm - 9:00 pm",
    "thursday_hours": "12:00 pm - 9:00 pm",
    "friday_hours": "12:00 pm - 10:00 pm",
    "saturday_hours": "12:00 pm - 10:00 pm",
    "sunday_hours": "12:00 pm - 9:00 pm",
    "facebook": "https://www.facebook.com/capturedbeerbus",
    "twitter": "Not Provided",
    "website": "Not Provided",
    "phone_number": "509-954-2136",
    "tags": ["Beer"]
  },
  {
    "name": "In & Out Kitchen",
    "address": "SE 82nd Ave & SE Harney St",
    "monday_hours": "11:00 am - 8:00 pm",
    "tuesday_hours": "11:00 am - 8:00 pm",
    "wednesday_hours": "11:00 am - 8:00 pm",
    "thursday_hours": "11:00 am - 8:00 pm",
    "friday_hours": "11:00 am - 8:00 pm",
    "saturday_hours": "11:00 am - 8:00 pm",
    "sunday_hours": "11:00 am - 7:00 pm",
    "facebook": "Not Provided",
    "twitter": "Not Provided",
    "website": "http://www.cartlandia.com/in-and-out-kitchen/",
    "phone_number": "971-998-3703",
    "tags": ["Vietnamese"]
  },
  {
    "name": "Juniper",
    "address": "3121 SW Moody Ave",
    "monday_hours": "8:00 am - 2:00 pm",
    "tuesday_hours": "8:00 am - 2:00 pm",
    "wednesday_hours": "8:00 am - 2:00 pm",
    "thursday_hours": "8:00 am - 2:00 pm",
    "friday_hours": "8:00 am - 2:00 pm",
    "saturday_hours": "11:00 am - 2:00 pm",
    "sunday_hours": "Closed",
    "facebook": "https://www.facebook.com/juniperpdx",
    "twitter": "https://twitter.com/junipercart",
    "website": "http://juniperpdx.com",
    "phone_number": "Not Provided",
    "tags": ["Vegan", "Gluten-Free"]
  },
  {
    "name": "Pyro’s Wicked Wiches",
    "address": "SE Division St and SE 28th Pl",
    "monday_hours": "Closed",
    "tuesday_hours": "Closed",
    "wednesday_hours": "12:00 pm - 3:00 pm",
    "thursday_hours": "12:00 pm - 8:00 pm",
    "friday_hours": "12:00 pm - 8:00 pm",
    "saturday_hours": "12:00 pm - 8:00 pm",
    "sunday_hours": "12:00 pm - 8:00 pm",
    "facebook": "https://www.facebook.com/pages/Pyro-Pizza-Cart/196863665802?ref=br_tf",
    "twitter": "http://twitter.com/PyroPizza",
    "website": "http://pyropizzacart.com/",
    "phone_number": "503-706-6344",
    "tags": ["Sandwiches"]
  },
  {
    "name": "Big Fat Weiners",
    "address": "NE 15th Avenue and NE Alberta Street",
    "monday_hours": "11:00 am - 10:00 pm",
    "tuesday_hours": "11:00 am - 10:00 pm",
    "wednesday_hours": "11:00 am - 10:00 pm",
    "thursday_hours": "11:00 am - 3:00 am",
    "friday_hours": "11:00 am - 3:00 am",
    "saturday_hours": "11:00 am - 3:00 am",
    "sunday_hours": "11:00 am - 6:00 pm",
    "facebook": "https://www.facebook.com/bignfatone/timeline",
    "twitter": "Not Provided",
    "website": "Not Provided",
    "phone_number": "Not Provided",
    "tags": ["Hot Dogs"]
  },
  {
    "name": "Desi PDX",
    "address": "1477 NE Alberta Street",
    "monday_hours": "Closed",
    "tuesday_hours": "Closed",
    "wednesday_hours": "Closed",
    "thursday_hours": "11:30 am - 8:00 pm",
    "friday_hours": "11:30 am - 8:00 pm",
    "saturday_hours": "11:30 am - 8:00 pm",
    "sunday_hours": "11:30 am - 7:30 pm",
    "facebook": "https://www.facebook.com/DesiPDX/timeline",
    "twitter": "http://twitter.com/desipdx",
    "website": "http://www.desipdx.com/",
    "phone_number": "503-862-3374",
    "tags": ["Indian", "Gluten-Free"]
  },
  {
    "name": "Kingsland Kitchen",
    "address": "SW 5th and Oak",
    "monday_hours": "8:00 am - 3:00 pm",
    "tuesday_hours": "8:00 am - 3:00 pm",
    "wednesday_hours": "8:00 am - 3:00 pm",
    "thursday_hours": "8:00 am - 3:00 pm",
    "friday_hours": "8:00 am - 3:00 pm",
    "saturday_hours": "Closed",
    "sunday_hours": "Closed",
    "facebook": "https://www.facebook.com/pages/Kingsland-Kitchen/338087413044502?fref=ts",
    "twitter": "https://twitter.com/kingslandpdx",
    "website": "http://www.kingslandkitchen.com/",
    "phone_number": "971-300-3118",
    "tags": ["British", "American"]
  },
  {
    "name": "Pulehu Pizza",
    "address": "113 SE 28th Ave",
    "monday_hours": "11:30 am - 3:30 pm",
    "tuesday_hours": "11:30 am - 3:30 pm",
    "wednesday_hours": "11:30 am - 3:30 pm",
    "thursday_hours": "11:30 am - 3:30 pm",
    "friday_hours": "11:30 am - 3:30 pm",
    "saturday_hours": "11:30 am - 3:30 pm and 11:00 pm to 4:00 am",
    "sunday_hours": "11:30 am - 3:30 pm and 11:00 pm to 4:00 am",
    "facebook": "https://www.facebook.com/pulehupizzaSE",
    "twitter": "Not Provided",
    "website": "http://pulehupizza.com/",
    "phone_number": "503-915-6869",
    "tags": ["Pizza"]
  },
  {
    "name": "Sam’s Saj",
    "address": "SW 10th and SW Washington St",
    "monday_hours": "11:00 am - 7:00 pm",
    "tuesday_hours": "11:00 am - 7:00 pm",
    "wednesday_hours": "11:00 am - 7:00 pm",
    "thursday_hours": "11:00 am - 7:00 pm",
    "friday_hours": "11:00 am - 7:00 pm",
    "saturday_hours": "11:00 am - 7:00 pm",
    "sunday_hours": "Closed",
    "facebook": "https://www.facebook.com/pages/Sams-Saj/548371501973419?sk=timeline",
    "twitter": "Not Provided",
    "website": "Not Provided",
    "phone_number": "Not Provided",
    "tags": ["Mediterranean", "Lebanese"]
  },
  {
    "name": "Bing Mi!",
    "address": "SW 9th and SW Alder St",
    "monday_hours": "7:30 am - 3:00 pm",
    "tuesday_hours": "7:30 am - 3:00 pm",
    "wednesday_hours": "7:30 am - 3:00 pm",
    "thursday_hours": "7:30 am - 3:00 pm",
    "friday_hours": "7:30 am - 3:00 pm",
    "saturday_hours": "11:00 am - 4:00 pm",
    "sunday_hours": "Closed",
    "facebook": "https://www.facebook.com/bingmifoodcart/",
    "twitter": "https://twitter.com/bing_mi",
    "website": "http://www.bingmiportland.com",
    "phone_number": "Not Provided",
    "tags": ["Chinese", "Creperies"]
  },
  {
    "name": "Dog Town Food Cart",
    "address": "SE Division St and SE 28th Pl",
    "monday_hours": "Closed",
    "tuesday_hours": "12:00pm - 8:00pm",
    "wednesday_hours": "3:00pm - 8:30pm",
    "thursday_hours": "12:00pm - 8:30pm",
    "friday_hours": "3:00 pm - 9:00 pm",
    "saturday_hours": "3:00 pm - 9:00 pm",
    "sunday_hours": "12:00pm - 3:00pm",
    "facebook": "https://www.facebook.com/dogtownfoodcart",
    "twitter": "http://twitter.com/dogtownpdx",
    "website": "http://Dogtownfoodcart.com",
    "phone_number": "Not Provided",
    "tags": ["Hot Dogs"]
  },
  {
    "name": "Monk’s",
    "address": "SE 43rd and SE Belmont St.",
    "monday_hours": "11:30 am - 8:00 pm",
    "tuesday_hours": "11:30 am - 8:00 pm",
    "wednesday_hours": "11:30 am - 8:00 pm",
    "thursday_hours": "11:30 am - 8:00 pm",
    "friday_hours": "11:30 am - 8:00 pm",
    "saturday_hours": "11:30 am - 8:00 pm",
    "sunday_hours": "11:30 am - 8:00 pm",
    "facebook": "https://www.facebook.com/monkspdx",
    "twitter": "Not Provided",
    "website": "Not Provided",
    "phone_number": "302-545-0708",
    "tags": ["Cheesesteaks", "Sandwiches"]
  },
  {
    "name": "Spielman Bagels Food Cart",
    "address": "SW 10th and SW Alder St.",
    "monday_hours": "7:30 am - 2:30 pm",
    "tuesday_hours": "7:30 am - 2:30 pm",
    "wednesday_hours": "7:30 am - 2:30 pm",
    "thursday_hours": "7:30 am - 2:30 pm",
    "friday_hours": "7:30 am - 2:30 pm",
    "saturday_hours": "Closed",
    "sunday_hours": "Closed",
    "facebook": "Not Provided",
    "twitter": "Not Provided",
    "website": "http://www.spielmanbagels.com/",
    "phone_number": "503-477-9045",
    "tags": ["Bagels"]
  },
  {
    "name": "Smak Dab’s",
    "address": "5221 NE Sandy Blvd",
    "monday_hours": "11:00 am - 8:00 pm",
    "tuesday_hours": "11:00 am - 8:00 pm",
    "wednesday_hours": "11:00 am - 8:00 pm",
    "thursday_hours": "11:00 am - 8:00 pm",
    "friday_hours": "11:00 am - 8:00 pm",
    "saturday_hours": "11:00 am - 8:00 pm",
    "sunday_hours": "Closed",
    "facebook": "https://www.facebook.com/SmakDabsPDX/timeline",
    "twitter": "https://twitter.com/smakdabs",
    "website": "http://smakdabs.wordpress.com",
    "phone_number": "503-489-7194",
    "tags": ["Burgers"]
  },
  {
    "name": "The Hot Box BBQ",
    "address": "3121 SW Moody Ave",
    "monday_hours": "11:00 am - 7:00 pm",
    "tuesday_hours": "11:00 am - 7:00 pm",
    "wednesday_hours": "11:00 am - 7:00 pm",
    "thursday_hours": "11:00 am - 7:00 pm",
    "friday_hours": "11:00 am - 7:00 pm",
    "saturday_hours": "Closed",
    "sunday_hours": "Closed",
    "facebook": "https://www.facebook.com/thehotboxca/timeline",
    "twitter": "https://twitter.com/thehotboxca",
    "website": "http://www.thehotboxbbq.com",
    "phone_number": "707-223-2511",
    "tags": ["American", "Barbeque"]
  },
  {
    "name": "Polli-Tico",
    "address": "1122 SE Tacoma St",
    "monday_hours": "11:00 am - 8:00 pm",
    "tuesday_hours": "11:00 am - 8:00 pm",
    "wednesday_hours": "11:00 am - 8:00 pm",
    "thursday_hours": "11:00 am - 8:00 pm",
    "friday_hours": "11:00 am - 8:00 pm",
    "saturday_hours": "11:00 am - 8:00 pm",
    "sunday_hours": "Closed",
    "facebook": "https://www.facebook.com/pollitico",
    "twitter": "http://twitter.com/PolliticoPDX",
    "website": "http://Polli-Tico.com",
    "phone_number": "971-258-2845",
    "tags": ["Peruvian", "Chicken Wings"]
  },
  {
    "name": "Scout Beer Garden",
    "address": "SE Division St and SE 28th Pl",
    "monday_hours": "12:00 pm - 9:00 pm",
    "tuesday_hours": "12:00 pm - 9:00 pm",
    "wednesday_hours": "12:00 pm - 9:00 pm",
    "thursday_hours": "12:00 pm - 9:00 pm",
    "friday_hours": "12:00 pm - 9:00 pm",
    "saturday_hours": "12:00 pm - 9:00 pm",
    "sunday_hours": "12:00 pm - 9:00 pm",
    "facebook": "https://www.facebook.com/scoutbeergarden/timeline",
    "twitter": "http://twitter.com/Scout_PDX",
    "website": "http://www.scoutpdx.com/",
    "phone_number": "650-255-8493",
    "tags": ["Beer"]
  },
  {
    "name": "La Camel",
    "address": "520 SW 9th Ave",
    "monday_hours": "11:00 am - 6:00 pm",
    "tuesday_hours": "11:00 am - 6:00 pm",
    "wednesday_hours": "11:00 am - 6:00 pm",
    "thursday_hours": "11:00 am - 6:00 pm",
    "friday_hours": "11:00 am - 6:00 pm",
    "saturday_hours": "11:00 am - 6:00 pm",
    "sunday_hours": "Closed",
    "facebook": "https://www.facebook.com/lacamelpdx",
    "twitter": "https://twitter.com/lacamelpdx",
    "website": "http://www.lacamel.com/",
    "phone_number": "503-778-0604",
    "tags": ["Moroccan"]
  },
  {
    "name": "Garden Monsters",
    "address": "SE Division St. and SE 28th Pl.",
    "monday_hours": "11:00 am - 8:00 pm",
    "tuesday_hours": "11:00 am - 8:00 pm",
    "wednesday_hours": "11:00 am - 8:00 pm",
    "thursday_hours": "11:00 am - 8:00 pm",
    "friday_hours": "11:00 am - 8:00 pm",
    "saturday_hours": "11:00 am - 8:00 pm",
    "sunday_hours": "11:30 am - 7:00 pm",
    "facebook": "http://facebooks.com/gardenmonsters",
    "twitter": "http://www.twitter.com/gardenmonsters",
    "website": "http://www.gardenmonsters.net",
    "phone_number": "503-688-8500",
    "tags": ["Salad", "Gluten-Free"]
  },
  {
    "name": "Chop Chop",
    "address": "SW 10th and SW Washington St.",
    "monday_hours": "11:30 am - 9:00 pm",
    "tuesday_hours": "11:30 am - 9:00 pm",
    "wednesday_hours": "11:30 am - 9:00 pm",
    "thursday_hours": "11:30 am - 5:30 pm",
    "friday_hours": "11:30 am - 9:30 pm",
    "saturday_hours": "11:30 am - 9:30 pm",
    "sunday_hours": "11:30 am - 9:00 pm",
    "facebook": "Not Provided",
    "twitter": "Not Provided",
    "website": "Not Provided",
    "phone_number": "503-998-0407",
    "tags": ["Chinese"]
  },
  {
    "name": "Haan Ghin",
    "address": "1875 SW Park Ave",
    "monday_hours": "11:00 am - 3:00 pm",
    "tuesday_hours": "11:00 am - 3:00 pm",
    "wednesday_hours": "11:00 am - 3:00 pm",
    "thursday_hours": "11:00 am - 3:00 pm",
    "friday_hours": "11:00 am - 3:00 pm",
    "saturday_hours": "Closed",
    "sunday_hours": "Closed",
    "facebook": "https://www.facebook.com/haanghin",
    "twitter": "http://twitter.com/haanghin",
    "website": "http://www.foodcartsportland.com/2015/01/06/haan-ghin/#more-10404",
    "phone_number": "Not Provided",
    "tags": ["Laotian"]
  },
  {
    "name": "IGPAY",
    "address": "4631 N Albina Ave",
    "monday_hours": "11:00 am - 6:00 pm",
    "tuesday_hours": "11:00 am - 6:00 pm",
    "wednesday_hours": "11:00 am - 6:00 pm",
    "thursday_hours": "11:00 am - 6:00 pm",
    "friday_hours": "11:00 am - 6:00 pm",
    "saturday_hours": "11:00 am - 6:00 pm",
    "sunday_hours": "11:00 am - 6:00 pm",
    "facebook": "https://www.facebook.com/IGPAY-Food-Cart-295814140620973/",
    "twitter": "https://twitter.com/igpayfoodcart",
    "website": "http://igpayportland.com/",
    "phone_number": "970-556-3280",
    "tags": ["American", "Sandwiches"]
  },
  {
    "name": "Buki",
    "address": "SE Division St and SE 28th Pl",
    "monday_hours": "12:00 pm - 3:30 pm and 5:30 pm - 8:00 pm",
    "tuesday_hours": "Closed",
    "wednesday_hours": "12:00 pm - 3:30 pm and 5:30 pm - 8:00 pm",
    "thursday_hours": "12:00 pm - 3:30 pm and 5:30 pm - 8:00 pm",
    "friday_hours": "12:00 pm - 9:00 pm",
    "saturday_hours": "12:00 pm - 9:00 pm",
    "sunday_hours": "12:00 pm - 8:00 pm",
    "facebook": "https://www.facebook.com/bukipdx",
    "twitter": "http://twitter.com/bukipdx",
    "website": "Not Provided",
    "phone_number": "360-931-1541",
    "tags": ["Japanese", "Taiwanese"]
  },
  {
    "name": "Neue Southern PDX",
    "address": "3200 SW Moody Ave",
    "monday_hours": "11:30 am - 3:30 pm",
    "tuesday_hours": "11:30 am - 3:30 pm and 5:30 pm - 8:30 pm",
    "wednesday_hours": "11:30 am - 3:30 pm",
    "thursday_hours": "11:30 am - 3:30 pm and 5:30 pm - 8:30 pm",
    "friday_hours": "11:30 am - 3:30 pm",
    "saturday_hours": "12:00 pm - 4:00 pm",
    "sunday_hours": "Closed",
    "facebook": "https://www.facebook.com/NeueSouthern",
    "twitter": "http://twitter.com/neuesouthern",
    "website": "http://www.neuesouthernpdx.com/",
    "phone_number": "Not Provided",
    "tags": ["Southern", "American"]
  },
  {
    "name": "Cackalack’s Hot Chicken Shack",
    "address": "NE 52nd Ave and Sandy Blvd",
    "monday_hours": "11:30 am - 2:30 pm",
    "tuesday_hours": "11:30 am - 2:30 pm",
    "wednesday_hours": "11:30 am - 2:30 pm",
    "thursday_hours": "11:30 am - 2:30 pm",
    "friday_hours": "11:30 am - 2:30 pm",
    "saturday_hours": "11:30 am - 2:30 pm",
    "sunday_hours": "11:30 am - 2:30 pm",
    "facebook": "https://www.facebook.com/pages/Cackalacks-Hot-Chicken-Shack/168887829830705",
    "twitter": "https://twitter.com/CACKALACKSpdx",
    "website": "http://www.cackalacks.com/",
    "phone_number": "503-891-8093",
    "tags": ["Southern", "American"]
  },
  {
    "name": "Earth Burgers",
    "address": "SE Division St and SE 28th Pl",
    "monday_hours": "Closed",
    "tuesday_hours": "Closed",
    "wednesday_hours": "12:00 pm - 3:00 pm and 5:30 pm - 8:00 pm",
    "thursday_hours": "12:00 pm - 3:00 pm and 5:30 pm - 8:00 pm",
    "friday_hours": "12:00 pm - 3:00 pm and 5:30 pm - 8:00 pm",
    "saturday_hours": "12:00 pm - 3:00 pm and 5:30 pm - 8:00 pm",
    "sunday_hours": "12:00 pm - 3:00 pm and 5:30 pm - 8:00 pm",
    "facebook": "https://www.facebook.com/EatAtEarthBurger",
    "twitter": "https://twitter.com/earthburgers",
    "website": "http://www.earthburgerspdx.com/",
    "phone_number": "Not Provided",
    "tags": ["Vegan", "Vegetarian"]
  },
  {
    "name": "Ingrid’s Scandinavian Food",
    "address": "SE Division St and SE 28th Pl",
    "monday_hours": "Closed",
    "tuesday_hours": "Closed",
    "wednesday_hours": "12:00 pm - 8:00 pm",
    "thursday_hours": "12:00 pm - 8:00 pm",
    "friday_hours": "12:00 pm - 8:00 pm",
    "saturday_hours": "12:00 pm - 8:00 pm",
    "sunday_hours": "12:00 pm - 8:00 pm",
    "facebook": "https://www.facebook.com/scandinaviandishes",
    "twitter": "https://twitter.com/ingridsfood",
    "website": "Not Provided",
    "phone_number": "971-570-5659",
    "tags": ["Scandinavian"]
  },
  {
    "name": "Midwest Pizza Co.",
    "address": "N Skidmore St and N Mississippi Ave",
    "monday_hours": "Closed",
    "tuesday_hours": "11:30 am - 4:00 pm",
    "wednesday_hours": "11:30 am - 4:00 pm",
    "thursday_hours": "11:30 am - 4:00 pm",
    "friday_hours": "11:30 am - 8:00 pm",
    "saturday_hours": "12:00 pm - 8:00 pm",
    "sunday_hours": "12:00 pm - 4:00 pm",
    "facebook": "https://www.facebook.com/midwestpizzacompany?ref=br_tf",
    "twitter": "http://twitter.com/MidwestPizzaCo",
    "website": "http://mwpizza.com",
    "phone_number": "503-697-4992",
    "tags": ["Pizza"]
  },
  {
    "name": "Luang Prabang",
    "address": "SE 13th Ave and SE Lexington St",
    "monday_hours": "11:00 am - 7:00 pm",
    "tuesday_hours": "11:00 am - 7:00 pm",
    "wednesday_hours": "11:00 am - 7:00 pm",
    "thursday_hours": "11:00 am - 7:00 pm",
    "friday_hours": "11:00 am - 7:00 pm",
    "saturday_hours": "11:00 am - 8:00 pm",
    "sunday_hours": "12:00 pm - 5:30 pm",
    "facebook": "Not Provided",
    "twitter": "Not Provided",
    "website": "Not Provided",
    "phone_number": "Not Provided",
    "tags": ["Laotian", "Thai"]
  },
  {
    "name": "Small Pharoah’s",
    "address": "SW 5th Ave and SW Stark St",
    "monday_hours": "Open 24 Hours",
    "tuesday_hours": "Open 24 Hours",
    "wednesday_hours": "Open 24 Hours",
    "thursday_hours": "Open 24 Hours",
    "friday_hours": "Open 24 Hours",
    "saturday_hours": "Open 24 Hours",
    "sunday_hours": "Open 24 Hours",
    "facebook": "https://www.facebook.com/pages/Small-Pharoahs/481727731881287",
    "twitter": "https://twitter.com/small_pharoah",
    "website": "http://www.smallpharaohfood.com/",
    "phone_number": "917-500-9181",
    "tags": ["Egyptian", "Halal"]
  },
  {
    "name": "Uncle Tsang’s Kitchen",
    "address": "2231-2237 NE Alberta Ct",
    "monday_hours": "Closed",
    "tuesday_hours": "11:00 am - 9:00 pm",
    "wednesday_hours": "11:00 am - 9:00 pm",
    "thursday_hours": "11:00 am - 9:00 pm",
    "friday_hours": "11:00 am - 9:00 pm",
    "saturday_hours": "12:00 pm - 9:00 pm",
    "sunday_hours": "12:00 pm - 9:00 pm",
    "facebook": "https://www.facebook.com/pages/Uncle-Tsangs-Kitchen/1547768275443531?sk=timeline",
    "twitter": "Not Provided",
    "website": "Not Provided",
    "phone_number": "Not Provided",
    "tags": ["Chinese"]
  },
  {
    "name": "Namu",
    "address": "4290 SE Belmont St",
    "monday_hours": "11:00 am - 7:30 pm",
    "tuesday_hours": "11:00 am - 7:30 pm",
    "wednesday_hours": "11:00 am - 7:30 pm",
    "thursday_hours": "11:00 am - 7:30 pm",
    "friday_hours": "11:00 am - 7:30 pm",
    "saturday_hours": "11:00 am - 7:30 pm",
    "sunday_hours": "11:00 am - 7:30 pm",
    "facebook": "https://www.facebook.com/Namu-Korean-Hawaiian-168341903200758/",
    "twitter": "Not Provided",
    "website": "http://www.namufoodcart.com",
    "phone_number": "503-828-4260",
    "tags": ["Korean", "Hawaiian"]
  },
  {
    "name": "Azul Tequila Taqueria",
    "address": "SE Division St and SE 28th Pl",
    "monday_hours": "11:00 am - 9:00 pm",
    "tuesday_hours": "11:00 am - 9:00 pm",
    "wednesday_hours": "11:00 am - 9:00 pm",
    "thursday_hours": "11:00 am - 9:00 pm",
    "friday_hours": "11:00 am - 9:00 pm",
    "saturday_hours": "11:00 am - 9:00 pm",
    "sunday_hours": "11:00 am - 9:00 pm",
    "facebook": "https://www.facebook.com/AzulTequilaMexicanTaqueria/",
    "twitter": "Not Provided",
    "website": "Not Provided",
    "phone_number": "Not Provided",
    "tags": ["Mexican"]
  },
  {
    "name": "E-san Thai",
    "address": "133 Southwest 2nd Ave and Pine St",
    "monday_hours": "11:00 am - 11:00 pm",
    "tuesday_hours": "11:00 am - 11:00 pm",
    "wednesday_hours": "11:00 am - 11:00 pm",
    "thursday_hours": "11:00 am - 11:00 pm",
    "friday_hours": "11:00 am - 11:00 pm",
    "saturday_hours": "12:00 pm - 11:00 pm",
    "sunday_hours": "12:00 pm - 11:00 pm",
    "facebook": "https://www.facebook.com/esanthai/",
    "twitter": "https://twitter.com/esan_thai",
    "website": "http://www.e-santhai.com/",
    "phone_number": "503-223-4090",
    "tags": ["Thai"]
  },
  {
    "name": "Holy Mole",
    "address": "SE 33rd Ave and SE Hawthorne Blvd",
    "monday_hours": "Closed",
    "tuesday_hours": "11:00 am - 3:00 pm",
    "wednesday_hours": "11:00 am - 3:00 pm",
    "thursday_hours": "11:00 am - 6:00 pm",
    "friday_hours": "11:00 am - 6:00 pm",
    "saturday_hours": "12:00 pm - 6:00 pm",
    "sunday_hours": "Closed",
    "facebook": "https://www.facebook.com/holymolepdx",
    "twitter": "http://twitter.com/holymolepdx",
    "website": "Not Provided",
    "phone_number": "Not Provided",
    "tags": ["Mexican"]
  },
  {
    "name": "Bacon PDX",
    "address": "NE 52nd Ave and Sandy Blvd",
    "monday_hours": "Closed",
    "tuesday_hours": "11:00 am - 7:00 pm",
    "wednesday_hours": "11:00 am - 7:00 pm",
    "thursday_hours": "11:00 am - 7:00 pm",
    "friday_hours": "11:00 am - 8:00 pm",
    "saturday_hours": "11:00 am - 8:00 pm",
    "sunday_hours": "11:00 am - 3:00 pm",
    "facebook": "https://www.facebook.com/BaconPDX",
    "twitter": "http://twitter.com/BaconPDX",
    "website": "http://baconpdx.com/",
    "phone_number": "503-610-6863",
    "tags": ["American", "Sandwiches"]
  },
  {
    "name": "Umai",
    "address": "SE 33rd Ave and SE Hawthorne Blvd",
    "monday_hours": "Closed",
    "tuesday_hours": "Closed",
    "wednesday_hours": "12:00 pm - 3:00 pm",
    "thursday_hours": "12:00 pm - 3:00 pm",
    "friday_hours": "11:00 am - 8:00 pm",
    "saturday_hours": "11:00 am - 8:00 pm",
    "sunday_hours": "11:00 am - 3:00 pm",
    "facebook": "https://www.facebook.com/umaipdx/timeline",
    "twitter": "https://twitter.com/umaipdx",
    "website": "http://umaipdx.com/",
    "phone_number": "503-502-4428",
    "tags": ["Japanese", "Ramen"]
  },
  {
    "name": "Go Cart",
    "address": "510 SE Martin Luther King Junior Blvd",
    "monday_hours": "Closed",
    "tuesday_hours": "10:00 am - 2:30 pm",
    "wednesday_hours": "10:00 am - 2:30 pm",
    "thursday_hours": "10:00 am - 2:30 pm",
    "friday_hours": "11:00 am - 8:00 pm",
    "saturday_hours": "Closed",
    "sunday_hours": "Closed",
    "facebook": "Not Provided",
    "twitter": "Not Provided",
    "website": "Not Provided",
    "phone_number": "Not Provided",
    "tags": ["American"]
  },
  {
    "name": "Russian Horse",
    "address": "1299 SE Lexington St",
    "monday_hours": "Closed",
    "tuesday_hours": "Closed",
    "wednesday_hours": "12:00 pm - 3:00 pm",
    "thursday_hours": "12:00 pm - 3:00 pm and 5:00pm - 7:00pm",
    "friday_hours":  "12:00 pm - 3:00 pm and 5:00pm - 7:00pm",
    "saturday_hours": "12:00 pm - 3:00 pm and 5:00pm - 7:00pm",
    "sunday_hours":  "12:00 pm - 3:00 pm",
    "facebook": "https://www.facebook.com/pages/Russian-Horse/252121598300087",
    "twitter": "https://twitter.com/russianhorsepdx",
    "website": "http://russianhorse.com/",
    "phone_number": "971-599-1346",
    "tags": ["Russian"]
  },
  {
    "name": "ASH woodfired",
    "address": "3200 SW Moody Ave",
    "monday_hours": "11:00 am - 9:00 pm",
    "tuesday_hours": "11:00 am - 9:00 pm",
    "wednesday_hours": "11:00 am - 9:00 pm",
    "thursday_hours": "11:00 am - 9:00 pm",
    "friday_hours": "11:00 am - 9:00 pm",
    "saturday_hours": "12:00 pm - 4:00 pm",
    "sunday_hours": "12:00 pm - 4:00 pm",
    "facebook": "https://www.facebook.com/pages/ASH-woodfired/679173368807935",
    "twitter": "https://twitter.com/ASHwoodfired",
    "website": "http://ashwoodfired.com/",
    "phone_number": "503-941-0196",
    "tags": ["Pizza"]
  },
  {
    "name": "Gastro Mania",
    "address": "NW 19th Ave and NW Quimby St",
    "monday_hours": "11:00 am - 3:00 pm",
    "tuesday_hours": "11:00 am - 3:00 pm",
    "wednesday_hours": "11:00 am - 3:00 pm",
    "thursday_hours": "11:00 am - 3:00 pm",
    "friday_hours": "11:00 am - 3:00 pm",
    "saturday_hours": "Closed",
    "sunday_hours": "Closed",
    "facebook": "https://www.facebook.com/gastromaniaportland",
    "twitter": "Not Provided",
    "website": "Not Provided",
    "phone_number": "503-689-3794",
    "tags": ["Mediterranean"]
  },
  {
    "name": "Casablanca Express",
    "address": "510 SE Martin Luther King Jr Blvd",
    "monday_hours": "11:00 am - 5:00 pm",
    "tuesday_hours": "11:00 am - 5:00 pm",
    "wednesday_hours": "11:00 am - 5:00 pm",
    "thursday_hours": "11:00 am - 5:00 pm",
    "friday_hours": "11:00 am - 5:00 pm",
    "saturday_hours": "11:00 am - 3:00 pm",
    "sunday_hours": "Closed",
    "facebook": "https://www.facebook.com/CasablancaExpress",
    "twitter": "Not Provided",
    "website": "http://www.casablancaexpresspdx.com/",
    "phone_number": "Not Provided",
    "tags": ["Mediterranean", "Moroccan"]
  },
  {
    "name": "Güero",
    "address": "113 SE 28th Av",
    "monday_hours": "11:30 am - 8:00 pm",
    "tuesday_hours": "11:30 am - 8:00 pm",
    "wednesday_hours": "11:30 am - 8:00 pm",
    "thursday_hours": "11:30 am - 8:00 pm",
    "friday_hours": "11:30 am - 9:00 pm",
    "saturday_hours": "11:30 am - 9:00 pm",
    "sunday_hours": "11:30 am - 8:00 pm",
    "facebook": "https://www.facebook.com/gueropdx",
    "twitter": "http://twitter.com/gueropdx",
    "website": "Not Provided",
    "phone_number": "503-887-9258",
    "tags": ["Mexican"]
  },
  {
    "name": "Deutschland Curry",
    "address": "SW 5th Ave and SW Stark St.",
    "monday_hours": "11:00 am - 3:00 pm",
    "tuesday_hours": "11:00 am - 3:00 pm",
    "wednesday_hours": "11:00 am - 3:00 pm",
    "thursday_hours": "11:00 am - 3:00 pm",
    "friday_hours": "11:00 am - 3:00 pm",
    "saturday_hours": "Closed",
    "sunday_hours": "Closed",
    "facebook": "https://www.facebook.com/deutschlandcurry",
    "twitter": "http://twitter.com/DeutschlandPDX",
    "website": "http://DeutschlandCurry.com",
    "phone_number": "503-866-5903",
    "tags": ["German"]
  },
  {
    "name": "El Local",
    "address": "523-535 SE Grand Ave",
    "monday_hours": "10:00 am - 9:00 pm",
    "tuesday_hours": "10:00 am - 9:00 pm",
    "wednesday_hours": "10:00 am - 9:00 pm",
    "thursday_hours": "10:00 am - 9:00 pm",
    "friday_hours": "10:00 am - 9:00 pm",
    "saturday_hours": "Closed",
    "sunday_hours": "Closed",
    "facebook": "Not Provided",
    "twitter": "Not Provided",
    "website": "http://cefoodcarts.com/our-carts/",
    "phone_number": "503-753-3661",
    "tags": ["Mexican"]
  },
  {
    "name": "Sila Thai",
    "address": "510 SE Martin Luther King Jr Blvd",
    "monday_hours": "11:30 am - 8:30 pm",
    "tuesday_hours": "11:30 am - 8:30 pm",
    "wednesday_hours": "11:30 am - 8:30 pm",
    "thursday_hours": "11:30 am - 8:30 pm",
    "friday_hours": "11:30 am - 8:30 pm",
    "saturday_hours": "10:30 am - 7:30 pm",
    "sunday_hours": "1:00 pm - 6:00 pm",
    "facebook": "https://www.facebook.com/pages/SiLa-Thai...Cart/124753504260933",
    "twitter": "Not Provided",
    "website": "Not Provided",
    "phone_number": "503-757-5410",
    "tags": ["Thai"]
  },
  {
    "name": "Dalo’s Kitchen",
    "address": "510 SE Martin Luther King Jr Blvd",
    "monday_hours": "11:00 am - 7:30 pm",
    "tuesday_hours": "11:00 am - 7:30 pm",
    "wednesday_hours": "11:00 am - 7:30 pm",
    "thursday_hours": "11:00 am - 7:30 pm",
    "friday_hours": "11:00 am - 9:00 pm",
    "saturday_hours": "11:00 am - 9:00 pm",
    "sunday_hours": "Closed",
    "facebook": "https://www.facebook.com/Dalos-Ethiopian-Kitchen-164623730237485/",
    "twitter": "Not Provided",
    "website": "http://www.dalos-kitchen.com/",
    "phone_number": "503-740-0313",
    "tags": ["Ethiopian"]
  },
  {
    "name": "Olé Latte Coffee",
    "address": "SW 5th and SW Harrison St",
    "monday_hours": "7:00 am - 5:00 pm",
    "tuesday_hours": "7:00 am - 5:00 pm",
    "wednesday_hours": "7:00 am - 5:00 pm",
    "thursday_hours": "7:00 am - 5:00 pm",
    "friday_hours": "7:00 am - 5:00 pm",
    "saturday_hours": "8:00 am - 3:00 pm",
    "sunday_hours": "Closed",
    "facebook": "https://www.facebook.com/OleLatteCoffee",
    "twitter": "https://twitter.com/OleLatteCoffee",
    "website": "http://www.olelatte.com",
    "phone_number": "971-221-6318",
    "tags": ["Coffee", "Tea"]
  },
  {
    "name": "Mama Chow’s Kitchen",
    "address": "SW 2nd Ave and SW Stark St",
    "monday_hours": "11:00 am - 3:00 pm",
    "tuesday_hours": "11:00 am - 3:00 pm",
    "wednesday_hours": "11:00 am - 3:00 pm",
    "thursday_hours": "11:00 am - 3:00 pm",
    "friday_hours": "11:00 am - 3:00 pm",
    "saturday_hours": "Closed",
    "sunday_hours": "Closed",
    "facebook": "https://www.facebook.com/mamachowskitchen",
    "twitter": "https://twitter.com/MamaCsKitchen",
    "website": "Not Provided",
    "phone_number": "Not Provided",
    "tags": ["Chicken Wings", "Chinese"]
  },
  {
    "name": "PDX Sliders",
    "address": "8064 SE 17th Ave",
    "monday_hours": "11:00 am - 7:00 pm",
    "tuesday_hours": "11:00 am - 7:00 pm",
    "wednesday_hours": "11:00 am - 7:00 pm",
    "thursday_hours": "11:00 am - 7:00 pm",
    "friday_hours": "11:00 am - 7:00 pm",
    "saturday_hours": "11:00 am - 7:00 pm",
    "sunday_hours": "12:00 pm - 7:00 pm",
    "facebook": "https://www.facebook.com/pdxsliders",
    "twitter": "http://twitter.com/pdxsliders",
    "website": "http://www.pdxsliders.com/",
    "phone_number": "971-717-5271",
    "tags": ["Burgers", "American"]
  },
  {
    "name": "Thick",
    "address": "SW 9th St and SW Washington St",
    "monday_hours": "11:30 am - 2:00 pm and 5:00 pm - 9:00 pm",
    "tuesday_hours": "11:30 am - 2:00 pm and 5:00 pm - 9:00 pm",
    "wednesday_hours": "11:30 am - 2:00 pm and 5:00 pm - 9:00 pm",
    "thursday_hours": "11:30 am - 2:00 pm and 5:00 pm - 9:00 pm",
    "friday_hours": "11:30 am - 2:00 pm and 5:00 pm - 9:00 pm",
    "saturday_hours": "2:00 pm - 9:00 pm",
    "sunday_hours": "Closed",
    "facebook": "https://www.facebook.com/thickpizza",
    "twitter": "https://twitter.com/thickpdx",
    "website": "Not Provided",
    "phone_number": "630-697-6581",
    "tags": ["Pizza"]
  },
  {
    "name": "El Pilón",
    "address": "SW 2nd St and Oak St",
    "monday_hours": "10:00 am - 7:00 pm",
    "tuesday_hours": "10:00 am - 7:00 pm",
    "wednesday_hours": "10:00 am - 7:00 pm",
    "thursday_hours": "10:00 am - 7:00 pm",
    "friday_hours": "10:00 am - 7:00 pm",
    "saturday_hours": "10:00 am - 7:00 pm",
    "sunday_hours": "10:00 am - 7:00 pm",
    "facebook": "https://www.facebook.com/pages/El-Pilon/129790060551563",
    "twitter": "Not Provided",
    "website": "Not Provided",
    "phone_number": "Not Provided",
    "tags": ["Colombian"]
  },
  {
    "name": "Maine Street Lobster Company",
    "address": "8145 SE 82nd Ave",
    "monday_hours": "11:30 am - 7:30 pm",
    "tuesday_hours": "11:30 am - 7:30 pm",
    "wednesday_hours": "11:30 am - 7:30 pm",
    "thursday_hours": "11:30 am - 7:30 pm",
    "friday_hours": "11:30 am - 7:30 pm",
    "saturday_hours": "11:30 am - 7:30 pm",
    "sunday_hours": "12:00 pm - 5:00 pm",
    "facebook": "https://www.facebook.com/MaineStreetLobsterCompany",
    "twitter": "http://twitter.com/MaineStLobster",
    "website": "http://MaineStreetLobsterCompany.com",
    "phone_number": "770-480-3437",
    "tags": ["Seafood"]
  },
  {
    "name": "Los Alambres Torteria Taqueria",
    "address": "1134 SE 82nd Ave",
    "monday_hours": "11:00 am - 5:00 pm",
    "tuesday_hours": "9:00 am - 10:00 pm",
    "wednesday_hours": "9:00 am - 10:00 pm",
    "thursday_hours": "9:00 am - 10:00 pm",
    "friday_hours": "9:00 am - 10:00 pm",
    "saturday_hours": "9:00 am - 10:00 pm",
    "sunday_hours": "10:00 am - 6:00 pm",
    "facebook": "https://www.facebook.com/pages/Los-Alambres-Torteria-Taqueria-DF/116607791829995",
    "twitter": "Not Provided",
    "website": "http://losalambresdf.weebly.com/",
    "phone_number": "503-213-0085",
    "tags": ["Mexican"]
  },
  {
    "name": "Hapa Ramen",
    "address": "SE 28th Pl. and Division St",
    "monday_hours": "5:00 pm - 8:30 pm",
    "tuesday_hours": "5:00 pm - 8:30 pm",
    "wednesday_hours": "5:00 pm - 8:30 pm",
    "thursday_hours": "5:00 pm - 8:30 pm",
    "friday_hours": "5:00 pm - 8:30 pm",
    "saturday_hours": "12:00 pm - 9:00 pm",
    "sunday_hours": "12:00 pm - 8:00 pm",
    "facebook": "https://www.facebook.com/pages/Hapa-Ramen-PDX/419811661451647",
    "twitter": "http://twitter.com/HapaPdx",
    "website": "http://hapapdx.com",
    "phone_number": "503-560-0393",
    "tags": ["Ramen", "Japanese"]
  },
  {
    "name": "Plane Pastries",
    "address": "SE Foster Rd and SE 52nd Ave",
    "monday_hours": "10:00 am - 3:00 pm",
    "tuesday_hours": "Closed",
    "wednesday_hours": "10:00 am - 3:00 pm",
    "thursday_hours": "10:00 am - 3:00 pm",
    "friday_hours": "10:00 am - 3:00 pm",
    "saturday_hours": "9:00 am - 3:00 pm",
    "sunday_hours": "9:00 am - 3:00 pm",
    "facebook": "https://www.facebook.com/PlanePastries",
    "twitter": "http://twitter.com/planepastries",
    "website": "http://www.planepastries.com/",
    "phone_number": "402-917-0683",
    "tags": ["Bakery"]
  },
  {
    "name": "Brazilian House",
    "address": "SE Belmont St & SE 43rd Ave",
    "monday_hours": "12:00 pm - 8:00 pm",
    "tuesday_hours": "Closed",
    "wednesday_hours": "12:00 pm - 8:00 pm",
    "thursday_hours": "12:00 pm - 8:00 pm",
    "friday_hours": "12:00 pm - 8:00 pm",
    "saturday_hours": "12:00 pm - 8:00 pm",
    "sunday_hours": "12:00 pm - 8:00 pm",
    "facebook": "https://www.facebook.com/Brazilian-House-1420097194873209/",
    "twitter": "Not Provided",
    "website": "Not Provided",
    "phone_number": "503-360-7688",
    "tags": ["Brazilian"]
  },
  {
    "name": "Pizza Contadino",
    "address": "N. Richmond at N. Lombard",
    "monday_hours": "Closed",
    "tuesday_hours": "2:00 pm - 11:00 pm",
    "wednesday_hours": "2:00 pm - 11:00 pm",
    "thursday_hours": "2:00 pm - 11:00 pm",
    "friday_hours": "2:00 pm - 11:00 pm",
    "saturday_hours": "2:00 pm - 11:00 pm",
    "sunday_hours": "1:00 pm - 8:00 pm",
    "facebook": "https://www.facebook.com/Pizza-Contadino-146427445389345/",
    "twitter": "Not Provided",
    "website": "Not Provided",
    "phone_number": "503-935-4375",
    "tags": ["Pizza"]
  },
  {
    "name": "Bridgetown Bagel Company",
    "address": "NE Sandy Blvd & NE 52nd Ave",
    "monday_hours": "Closed",
    "tuesday_hours": "Closed",
    "wednesday_hours": "7:00 am - 2:00 pm",
    "thursday_hours": "7:00 am - 2:00 pm",
    "friday_hours": "7:00 am - 2:00 pm",
    "saturday_hours": "8:00 am - 3:00 pm",
    "sunday_hours": "8:00 am - 3:00 pm",
    "facebook": "https://www.facebook.com/bridgetownbagel",
    "twitter": "https://twitter.com/bridgetownbagel",
    "website": "http://www.bridgetownbagel.com",
    "phone_number": "503-268-2522",
    "tags": ["Bagels"]
  },
  {
    "name": "Fried Egg I’m In Love",
    "address": "3207 SE Hawthorne Blvd",
    "monday_hours": "Closed",
    "tuesday_hours": "8:30 am - 2:00 pm",
    "wednesday_hours": "8:30 am - 2:00 pm",
    "thursday_hours": "8:30 am - 2:00 pm",
    "friday_hours": "8:30 am - 2:00 pm",
    "saturday_hours": "9:00 am - 3:00 pm",
    "sunday_hours": "9:00 am - 3:00 pm",
    "facebook": "http://facebook.com/friedegglove",
    "twitter": "http://twitter.com/friedegglove",
    "website": "http://www.friedegglove.com",
    "phone_number": "503-610-3447",
    "tags": ["Sandwiches", "Breakfast & Brunch"]
  }
]


# Accounts
User.create({username: 'test', email: 'test@test.com', password: 'password'})

# Create Objects
food_carts.each do |cart_obj|
  new_cart = FoodCart.create(cart_obj.except(:tags))
  new_cart.tag_list.add(cart_obj[:tags])
  new_cart.save
  sleep 0.25
end
